# Site settings
title: Sketch Developers
email: developers@sketchapp.com
url: "http://developer.sketchapp.com"
github_repo:  https://github.com/BohemianCoding/developer.sketchapp.com

# Build settings
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    fenced_code_blocks: true
    default_lang: javascript
    span:
      disable: true

sass:
  style: compressed
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - .sass-cache
  - README.md

# Dynamic Content
collections:
  reference:
    output: true
    permalink: /reference/:path/
  code-examples:
    output: true
    permalink: /code-examples/:path/
  introduction:
    output: true
    permalink: /introduction/:path/
  blog-posts:
    output: true
    permalink: /blog/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single-page"
  -
    scope:
      type: "reference"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "code-examples"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "introduction"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "blog-posts"
    values:
      layout: "blog-post"
