# Site settings
title: Sketch Developers
email: developers@sketchapp.com
baseurl: "/developer.sketchapp.com" # the subpath of your site, e.g. /blog/
url: "https://bohemiancoding.github.io" # need to change this when we use our own site
github_repo:  https://github.com/BohemianCoding/developer.sketchapp.com

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'fenced_code_blocks', 'autolink']
sass:
  style: compressed

# Dynamic Content
collections:
  classes:
    output: true
    permalink: /docs/:path/
  examples:
    output: true
    permalink: /examples/:path/

# Defaults
defaults:
  - scope:
      path: "docs"
    values:
      layout: "class"
