# Site settings
title: Sketch Developers
email: developers@sketchapp.com
url: "http://developer.sketchapp.com"
github_repo:  https://github.com/BohemianCoding/developer.sketchapp.com

# Build settings
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    fenced_code_blocks: true
    default_lang: javascript
    span:
      disable: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

sass:
  style: compressed
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - .sass-cache
  - README.md

# Dynamic Content
collections:
  classes:
    output: true
    permalink: /reference/class/:path/
  actions:
    output: true
    permalink: /reference/action/:path/
  api:
    output: true
    permalink: /reference/api/:path/
  code-examples:
    output: true
    permalink: /examples/code/:path/
  introduction:
    output: true
    permalink: /introduction/:path/
  posts:
    output: true
    permalink: /blog/:path/
  plugins:
    output: true
    permalink: /examples/plugins/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single-page"
  -
    scope:
      type: "classes"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "api"
    values:
      layout: "docco-page"
  -
    scope:
      type: "actions"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "plugins"
    values:
      layout: "docco-page"
  -
    scope:
      type: "code-examples"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "introduction"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
