# Site settings
title: Sketch Developers
email: developers@sketchapp.com
url: "https://developer.bohemiancoding.com" # need to change this when we use our own site
github_repo:  https://github.com/BohemianCoding/developer.sketchapp.com

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'with_toc_data']
sass:
  style: compressed

# Dynamic Content
collections:
  classes:
    output: true
    permalink: /docs/:path/
  examples:
    output: true
    permalink: /examples/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "docs"
      type: "classes"
    values:
      layout: "class"
