# Site settings
title: Sketch Developers
email: developers@sketchapp.com
baseurl: "/developer.sketchapp.com/" # the subpath of your site, e.g. /blog/
url: "https://bohemiancoding.github.io" # need to change this when we use our own site
twitter_username: sketchapp
github_username:  BohemianCoding

# Build settings
markdown: kramdown

# Dynamic Content
collections:
  classes:
    output: true
    permalink: /docs/:path/
