# Site settings
title: Sketch Developers
email: developers@sketchapp.com
url: "http://developer.sketchapp.com"
github_repo:  https://github.com/BohemianCoding/developer.sketchapp.com

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'with_toc_data']
sass:
  style: compressed
exclude: [node_modules, gulpfile.js]

# Dynamic Content
collections:
  reference:
    output: true
    permalink: /reference/:path/
  code-examples:
    output: true
    permalink: /code-examples/:path/
  introduction:
    output: true
    permalink: /introduction/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "single-page"
  -
    scope:
      type: "reference"
    values:
      layout: "sidebar-page"
  -
    scope:
      type: "code-examples"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
  -
    scope:
      type: "introduction"
    values:
      layout: "sidebar-page"
      script: "/js/search.js"
